version: '3'
services:
  api:
    build:
      context: ./api
      args:
        - WORKDIR=${WORKDIR}
    volumes:
      - ${HOSTDIR}:${WORKDIR}

  web:
    build:
      context: ./web
      args:
        - WORKDIR=${WORKDIR}
    volumes:
      - ${HOSTDIR}:${WORKDIR}
    ports:
        - "8016:80"
    links:
      - api
    depends_on:
      - api
